/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uas;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author MyJourney
 */
public class GeraiZakat extends javax.swing.JFrame {
    String namalengkap = "",gender = "",nohp,alamat = "",pilihan;
    int biaya_admin;        
    double penghasilan, nishab =0.025,total_zakat, masukan, kembalian;
    
    
    
    /**
     * Creates new form GeraiZakat
     */
    
    public GeraiZakat() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_GrupGender = new javax.swing.ButtonGroup();
        body_Panel = new javax.swing.JPanel();
        menu_Panel = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        btn_biodata = new javax.swing.JButton();
        btn_refresh = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        btn_abouts = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        main_Panel = new javax.swing.JPanel();
        home_Panel = new javax.swing.JPanel();
        lbl_JudulAplikasi = new javax.swing.JLabel();
        lbl_version = new javax.swing.JLabel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_developed = new javax.swing.JLabel();
        lbl_nama = new javax.swing.JLabel();
        lbl_logo = new javax.swing.JLabel();
        lbl_copyright = new javax.swing.JLabel();
        biodata_Panel = new javax.swing.JPanel();
        lbl_JudulBiodata = new javax.swing.JLabel();
        lbl_NamaLengkap = new javax.swing.JLabel();
        lbl_JeniisKelamin = new javax.swing.JLabel();
        lbl_NoHp = new javax.swing.JLabel();
        lbl_Penghasilan = new javax.swing.JLabel();
        lbl_UangPembayaran = new javax.swing.JLabel();
        lbl_MetodePembayaran = new javax.swing.JLabel();
        lbl_BiayaAdmin = new javax.swing.JLabel();
        lbl_alamat = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        btn_pria = new javax.swing.JRadioButton();
        btn_wanita = new javax.swing.JRadioButton();
        txt_nohp = new javax.swing.JFormattedTextField();
        txt_penghasilan = new javax.swing.JTextField();
        txt_pembayaran = new javax.swing.JTextField();
        cb_bayar = new javax.swing.JComboBox<>();
        lbl_rp = new javax.swing.JLabel();
        lbl_duit = new javax.swing.JLabel();
        scrollpanel_alamat = new javax.swing.JScrollPane();
        txt_alamat = new javax.swing.JTextArea();
        bayar_Panel = new javax.swing.JPanel();
        lbl_NotaPembayaran = new javax.swing.JLabel();
        ScrollPanel_nota = new javax.swing.JScrollPane();
        txt_nota = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerai Zakat");

        body_Panel.setBackground(new java.awt.Color(250, 128, 114));

        menu_Panel.setBackground(new java.awt.Color(250, 128, 114));
        menu_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        btn_home.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\home_black_18x18.png")); // NOI18N
        btn_home.setText("HOME");
        btn_home.setIconTextGap(10);
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_biodata.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\perm_identity_black_18x18.png")); // NOI18N
        btn_biodata.setText("ISI BIODATA");
        btn_biodata.setIconTextGap(3);
        btn_biodata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_biodataActionPerformed(evt);
            }
        });

        btn_refresh.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\autorenew_black_18x18.png")); // NOI18N
        btn_refresh.setText("REFRESH");
        btn_refresh.setIconTextGap(5);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });

        btn_bayar.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\payment_black_18x18.png")); // NOI18N
        btn_bayar.setText("BAYAR");
        btn_bayar.setIconTextGap(10);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });

        btn_abouts.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\info_outline_black_18x18.png")); // NOI18N
        btn_abouts.setText("ABOUTS");
        btn_abouts.setIconTextGap(10);
        btn_abouts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aboutsActionPerformed(evt);
            }
        });

        btn_exit.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\exit_to_app_black_18x18.png")); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.setIconTextGap(20);
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menu_PanelLayout = new javax.swing.GroupLayout(menu_Panel);
        menu_Panel.setLayout(menu_PanelLayout);
        menu_PanelLayout.setHorizontalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_abouts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_biodata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(menu_PanelLayout.createSequentialGroup()
                        .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menu_PanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        menu_PanelLayout.setVerticalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_PanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btn_biodata, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btn_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btn_abouts, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        main_Panel.setBackground(new java.awt.Color(46, 204, 113));
        main_Panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        main_Panel.setLayout(new java.awt.CardLayout());

        home_Panel.setBackground(new java.awt.Color(152, 251, 152));

        lbl_JudulAplikasi.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lbl_JudulAplikasi.setText("Gerai Zakat Application");

        lbl_version.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        lbl_version.setText("v1.0");

        lbl_welcome.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_welcome.setText("Selamat Datang di Gerai Zakat");

        lbl_developed.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_developed.setText("Developed by :");

        lbl_nama.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_nama.setText("Muhammad Aswin Sigit");

        lbl_logo.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\Punctuation Unicode Characters _ Material UI_files\\gn-conceptual-design-vector-23975541.png")); // NOI18N

        lbl_copyright.setFont(new java.awt.Font("Times New Roman", 2, 20)); // NOI18N
        lbl_copyright.setIcon(new javax.swing.ImageIcon("D:\\Kuliah\\Semester 2\\Analisa Algoritma\\copyright_black_18x18.png")); // NOI18N
        lbl_copyright.setText("Copyright 2020");

        javax.swing.GroupLayout home_PanelLayout = new javax.swing.GroupLayout(home_Panel);
        home_Panel.setLayout(home_PanelLayout);
        home_PanelLayout.setHorizontalGroup(
            home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_PanelLayout.createSequentialGroup()
                .addGroup(home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(home_PanelLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_welcome)
                            .addComponent(lbl_JudulAplikasi, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_logo)))
                    .addGroup(home_PanelLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lbl_copyright))
                    .addGroup(home_PanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lbl_nama))
                    .addGroup(home_PanelLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(lbl_developed))
                    .addGroup(home_PanelLayout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        home_PanelLayout.setVerticalGroup(
            home_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_JudulAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_version, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(lbl_welcome)
                .addGap(18, 18, 18)
                .addComponent(lbl_developed)
                .addGap(18, 18, 18)
                .addComponent(lbl_nama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lbl_logo)
                .addGap(34, 34, 34)
                .addComponent(lbl_copyright)
                .addContainerGap())
        );

        main_Panel.add(home_Panel, "card2");

        biodata_Panel.setBackground(new java.awt.Color(240, 248, 255));

        lbl_JudulBiodata.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_JudulBiodata.setText("Silahkan Isi Biodata ");

        lbl_NamaLengkap.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_NamaLengkap.setText("Nama Lengkap");

        lbl_JeniisKelamin.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_JeniisKelamin.setText("Jenis Kelamin");

        lbl_NoHp.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_NoHp.setText("No Handphone");

        lbl_Penghasilan.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_Penghasilan.setText("Total Penghasilan Bersih");

        lbl_UangPembayaran.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_UangPembayaran.setText("Masukkan Uang Pembayaran");

        lbl_MetodePembayaran.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_MetodePembayaran.setText("Metode Pembayaran");

        lbl_BiayaAdmin.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_BiayaAdmin.setText("Biaya Admin");

        lbl_alamat.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        lbl_alamat.setText("Alamat");

        btn_GrupGender.add(btn_pria);
        btn_pria.setText("Pria");

        btn_GrupGender.add(btn_wanita);
        btn_wanita.setText("Wanita");

        txt_nohp.setColumns(13);
        try {
            txt_nohp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txt_nohp.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cb_bayar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Metode Pembayaran", "OVO", "GoPay", "DANA", "SAKU", " " }));
        cb_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_bayarActionPerformed(evt);
            }
        });

        lbl_rp.setText("Rp.");

        lbl_duit.setText("0");

        txt_alamat.setColumns(20);
        txt_alamat.setRows(5);
        scrollpanel_alamat.setViewportView(txt_alamat);

        javax.swing.GroupLayout biodata_PanelLayout = new javax.swing.GroupLayout(biodata_Panel);
        biodata_Panel.setLayout(biodata_PanelLayout);
        biodata_PanelLayout.setHorizontalGroup(
            biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biodata_PanelLayout.createSequentialGroup()
                        .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_NamaLengkap)
                            .addComponent(lbl_alamat))
                        .addGap(110, 110, 110)
                        .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(biodata_PanelLayout.createSequentialGroup()
                                .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(biodata_PanelLayout.createSequentialGroup()
                                .addComponent(scrollpanel_alamat)
                                .addContainerGap())))
                    .addGroup(biodata_PanelLayout.createSequentialGroup()
                        .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Penghasilan)
                            .addComponent(lbl_NoHp)
                            .addComponent(lbl_JeniisKelamin)
                            .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_UangPembayaran, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_MetodePembayaran))
                            .addComponent(lbl_BiayaAdmin))
                        .addGap(18, 18, 18)
                        .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(biodata_PanelLayout.createSequentialGroup()
                                .addComponent(lbl_rp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_duit))
                            .addGroup(biodata_PanelLayout.createSequentialGroup()
                                .addComponent(btn_pria, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_wanita, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cb_bayar, 0, 173, Short.MAX_VALUE)
                            .addComponent(txt_nohp)
                            .addComponent(txt_penghasilan)
                            .addComponent(txt_pembayaran))
                        .addContainerGap(47, Short.MAX_VALUE))))
            .addGroup(biodata_PanelLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(lbl_JudulBiodata)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        biodata_PanelLayout.setVerticalGroup(
            biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodata_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_JudulBiodata)
                .addGap(31, 31, 31)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_NamaLengkap))
                .addGap(18, 18, 18)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_wanita, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pria, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_JeniisKelamin))
                .addGap(26, 26, 26)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_NoHp)
                    .addComponent(txt_nohp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Penghasilan)
                    .addComponent(txt_penghasilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(biodata_PanelLayout.createSequentialGroup()
                        .addComponent(lbl_UangPembayaran)
                        .addGap(36, 36, 36)
                        .addComponent(lbl_MetodePembayaran)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biodata_PanelLayout.createSequentialGroup()
                        .addComponent(txt_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_BiayaAdmin)
                    .addComponent(lbl_rp)
                    .addComponent(lbl_duit))
                .addGap(27, 27, 27)
                .addGroup(biodata_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpanel_alamat, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addGroup(biodata_PanelLayout.createSequentialGroup()
                        .addComponent(lbl_alamat)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        main_Panel.add(biodata_Panel, "card3");

        bayar_Panel.setBackground(new java.awt.Color(255, 248, 220));

        lbl_NotaPembayaran.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lbl_NotaPembayaran.setText("Nota Pembayaran");

        txt_nota.setEditable(false);
        txt_nota.setColumns(20);
        txt_nota.setRows(5);
        ScrollPanel_nota.setViewportView(txt_nota);

        javax.swing.GroupLayout bayar_PanelLayout = new javax.swing.GroupLayout(bayar_Panel);
        bayar_Panel.setLayout(bayar_PanelLayout);
        bayar_PanelLayout.setHorizontalGroup(
            bayar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayar_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPanel_nota, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(bayar_PanelLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(lbl_NotaPembayaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bayar_PanelLayout.setVerticalGroup(
            bayar_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bayar_PanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_NotaPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPanel_nota, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        main_Panel.add(bayar_Panel, "card4");

        javax.swing.GroupLayout body_PanelLayout = new javax.swing.GroupLayout(body_Panel);
        body_Panel.setLayout(body_PanelLayout);
        body_PanelLayout.setHorizontalGroup(
            body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(body_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
                .addContainerGap())
        );
        body_PanelLayout.setVerticalGroup(
            body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, body_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(body_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(main_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(menu_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(body_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        //Remove Panel
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
        
        //Add Panel
        main_Panel.add(home_Panel);
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_btn_homeActionPerformed

    private void btn_biodataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_biodataActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
                
        main_Panel.add(biodata_Panel);
        main_Panel.repaint();
        main_Panel.revalidate();
                      
    }//GEN-LAST:event_btn_biodataActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        main_Panel.removeAll();
        main_Panel.repaint();
        main_Panel.revalidate();
                
        main_Panel.add(bayar_Panel);
        main_Panel.repaint();
        main_Panel.revalidate();
                 
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Akan Melakukan Pembayaran","PERINGATAN",dialogBtn);
        
        if (dialogResult == 0){
            
        namalengkap = txt_nama.getText();    
                        
        if(btn_pria.isSelected()){            
            gender = btn_pria.getText();}        
        if(btn_wanita.isSelected()){
            gender = btn_wanita.getText(); } 
        
        nohp = txt_nohp.getText();
        int length = nohp.length();
                                 
        penghasilan = Double.parseDouble(txt_penghasilan.getText());
        
        masukan = Double.parseDouble(txt_pembayaran.getText()); 
        
        alamat = txt_alamat.getText();   
        
        total_zakat = nishab * penghasilan;   
        
        kembalian = masukan - total_zakat - biaya_admin; 
            
        JOptionPane.showMessageDialog(this, "Zakat yang Akan Di Serahkan Sebesar : " +total_zakat); }
        
        
        
        txt_nota.setText(
                "\n Nama Lengkap\t: " +namalengkap +
                "\n\n\n Jenis Kelamin\t\t: " +gender +
                "\n\n\n No Handphone\t\t: " +nohp +
                "\n\n\n Total Penghasilan Bersih\t: Rp." +penghasilan +
                "\n\n\n Uang Pembayaran\t: Rp." +masukan +
                "\n\n\n Total Zakat\t\t: Rp." +total_zakat +                
                "\n\n\n Metode Pembayaran\t: " +pilihan +
                "\n\n\n Biaya Admin\t\t: Rp." +biaya_admin +
                "\n\n Kembalian\t\t: Rp." +kembalian +
                "\n\n Alamat\t\t: " +alamat                
            );      
        
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void btn_aboutsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aboutsActionPerformed
        AboutView baru = new AboutView(); 
        baru.setVisible(true); 
    }//GEN-LAST:event_btn_aboutsActionPerformed

    private void cb_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_bayarActionPerformed
        pilihan = ""; 
        pilihan = (String) cb_bayar.getSelectedItem(); 
        switch(pilihan){
            case "OVO" :
                biaya_admin = 2000; break; 
            case "GoPay" :
                biaya_admin = 2500; break; 
            case "DANA" :
                biaya_admin = 3000;break;
            case "SAKU" :
                biaya_admin = 3500; break;
            default : 
                biaya_admin = 0;break; 
        }         
        lbl_duit.setText(Integer.toString(biaya_admin));                                           
    }//GEN-LAST:event_cb_bayarActionPerformed

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Akan Melakukan Refresh, \nDan Akan Melakukan Pengisian Ulang Biodata Diri", "PERINGATAN",dialogBtn);        
        if(dialogResult == 0){
        txt_nama.setText("");
        btn_GrupGender.clearSelection();
        txt_nohp.setText("");
        txt_alamat.setText("");
        txt_penghasilan.setText("");
        txt_pembayaran.setText("");
        cb_bayar.setSelectedIndex(0);
        txt_nota.setText(""); }
        
        
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Keluar ?", "PERINGATAN", dialogBtn);
        if(dialogResult == 0){
            System.exit(0);            
        }

        
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GeraiZakat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPanel_nota;
    private javax.swing.JPanel bayar_Panel;
    private javax.swing.JPanel biodata_Panel;
    private javax.swing.JPanel body_Panel;
    private javax.swing.ButtonGroup btn_GrupGender;
    private javax.swing.JButton btn_abouts;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_biodata;
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_home;
    private javax.swing.JRadioButton btn_pria;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JRadioButton btn_wanita;
    private javax.swing.JComboBox<String> cb_bayar;
    private javax.swing.JPanel home_Panel;
    private javax.swing.JLabel lbl_BiayaAdmin;
    private javax.swing.JLabel lbl_JeniisKelamin;
    private javax.swing.JLabel lbl_JudulAplikasi;
    private javax.swing.JLabel lbl_JudulBiodata;
    private javax.swing.JLabel lbl_MetodePembayaran;
    private javax.swing.JLabel lbl_NamaLengkap;
    private javax.swing.JLabel lbl_NoHp;
    private javax.swing.JLabel lbl_NotaPembayaran;
    private javax.swing.JLabel lbl_Penghasilan;
    private javax.swing.JLabel lbl_UangPembayaran;
    private javax.swing.JLabel lbl_alamat;
    private javax.swing.JLabel lbl_copyright;
    private javax.swing.JLabel lbl_developed;
    private javax.swing.JLabel lbl_duit;
    private javax.swing.JLabel lbl_logo;
    private javax.swing.JLabel lbl_nama;
    private javax.swing.JLabel lbl_rp;
    private javax.swing.JLabel lbl_version;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPanel main_Panel;
    private javax.swing.JPanel menu_Panel;
    private javax.swing.JScrollPane scrollpanel_alamat;
    private javax.swing.JTextArea txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JFormattedTextField txt_nohp;
    private javax.swing.JTextArea txt_nota;
    private javax.swing.JTextField txt_pembayaran;
    private javax.swing.JTextField txt_penghasilan;
    // End of variables declaration//GEN-END:variables
  
}
